### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by RToBeg** [NVlabs/dream-in-4d#3]
I found in the appendix that when you implemented the stage 1,  you used V100 32g.  However, by the time I ran the stage 1 for the first 5000 rounds,  I had already reached 34+g.  Once I reached 5000 rounds, the rendered images are converted from 64 * 64 to 256 * 256.  A V6000 graphics card would display a problem：  **Runtime Error:/data1/mcy/code/3D/tiny-CUD-nn/include/tiny-CUD-nn/gpu_cemory. h: 584 cuMemCreate (&m.handles.back()), N_bytes_to-allocate,&prop, 0) failed: CUDA-ERROR_OUT_OF-MEMORY**,  May I ask if it's a mistake in my settings or if you're using more than one V100?  Why is this happening？How can I solve this problem.
THANKS!

**Comment by zhengyuf** [comment]
hi, we indeed only used one V100 for stage 1. 

I think the memory required might also depend on the scene. Following the implementation in threestudio, we used some techniques to speed up nerf rendering, e.g. register the empty space so we do not need to query points in empty space. Therefore the actual memory required varies based on the specific nerf scene. This could be a possible reason, but we actually found one V100 to be enough in most of our experiments..

**Comment by RToBeg** [comment]
Thanks for your answer. I find that different prompts will cause different results. Some prompts will run, the others will display CUDA OF OUT MOMERY.

> hi, we indeed only used one V100 for stage 1.
> 
> I think the memory required might also depend on the scene. Following the implementation in threestudio, we used some techniques to speed up nerf rendering, e.g. register the empty space so we do not need to query points in empty space. Therefore the actual memory required varies based on the specific nerf scene. This could be a possible reason, but we actually found one V100 to be enough in most of our experiments..
